name: CommitLint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  commitlint:
    container:
      image: commitlint/commitlint:19.8.1@sha256:bbfb5e986b5da3962a114270f28e854413e5b89317dbbecb36ecaabbb46082bc
    runs-on: ubuntu-24.04
    steps:
      - run: env | sort
      - name: Validate the latest commit message with commitlint
        if: github.event_name == 'push'
        run: echo "${{ github.event.head_commit.message }}" | npx commitlint -x @commitlint/config-conventional
      - name: Validate pull request title with commitlint
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint -x @commitlint/config-conventional
