name: Read the Docs Pull Request Preview
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  documentation-links:
    runs-on: ubuntu-24.04
    steps:
      - name: Add Read the Docs preview's link to pull request
        uses: readthedocs/actions/preview@b8bba1484329bda1a3abe986df7ebc80a8950333 # v1.5
        with:
          project-slug: ss-python
on:
  pull_request_target:
    types:
      - opened
    paths:
      - .github/workflows/readthedocs-preview.yml
      - .readthedocs.yaml
      - Makefile
      - README.md
      - docs/**
      - pdm.dev.lock
      - pdm.lock
permissions:
  pull-requests: write
